apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster
  region: eu-north-1
availabilityZones:
- eu-north-1
managedNodeGroups:
- name: on-demand
  labels:
    role: on-demand
  instanceType: t2.small
  desiredCapacity: 1
  volumeSize: 20
